### ISSUE TITLE
Nad configuration settings not available

### ISSUE THREAD

**Issue by gferreroferri** [Aemi-Studio/Nad#3]
I have installed the app on the latest iOS18 dev beta and I do not see any configuration per page, nor permission to any page. I am not so sure how this adblocker works. Is there any way to fine tune or report any ad or annoyance not blocked?

**Comment by g-cqd** [comment]
At the moment, the only way to report anything is to fill issue here or contact me anywhere you want so. The lack of reporting method is inherited from the policy of the app not dealing with any data from users.

That said. A clarification will be added in the app. A kind of user manual, because as of current state, Nad is a content blocker, and therefore you can fine-tune its behaviour using Safari features directly.
<img width="629" alt="image" src="https://github.com/user-attachments/assets/f79effa8-b484-4abc-b6e8-cfccd678280e">
<img width="842" alt="image" src="https://github.com/user-attachments/assets/ac1a6fdb-92c7-46fa-8702-9558f09247f1">
Disabling content blocker from this setting, also disables Nad.
This can be fine-tuned here:
<img width="948" alt="image" src="https://github.com/user-attachments/assets/18a22d37-2fcd-46c3-8835-aea1e73445ef">

**Comment by gferreroferri** [comment]
Thanks for the clarification!
